"""add_total_duration_ms

Revision ID: 064b94329b13
Revises: 284fa97d5297
Create Date: 2026-01-03 16:56:25.762656

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "064b94329b13"
down_revision: Union[str, Sequence[str], None] = "284fa97d5297"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("playlist", sa.Column("total_duration_ms", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("playlist", "total_duration_ms")
    # ### end Alembic commands ###
