"""add_public_profile_and_social_features

Revision ID: 09010338c349
Revises: 61c06cf72635
Create Date: 2025-12-31 19:09:53.199793

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "09010338c349"
down_revision: Union[str, Sequence[str], None] = "61c06cf72635"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_favorite_playlists",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("playlist_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["playlist_id"], ["playlist.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "playlist_id"),
    )
    op.add_column("playlist", sa.Column("source_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        "playlist_source_id_fkey",
        "playlist",
        "playlist",
        ["source_id"],
        ["id"],
        ondelete="SET NULL",
    )

    # Add columns as nullable first
    op.add_column("user", sa.Column("is_public", sa.Boolean(), nullable=True))
    op.add_column("user", sa.Column("favorite_artists", sa.JSON(), nullable=True))
    op.add_column("user", sa.Column("unskippable_albums", sa.JSON(), nullable=True))

    # Set default values for existing rows
    op.execute('UPDATE "user" SET is_public = true')
    op.execute("UPDATE \"user\" SET favorite_artists = '[]'::json")
    op.execute("UPDATE \"user\" SET unskippable_albums = '[]'::json")

    # Now make them non-nullable
    op.alter_column("user", "is_public", nullable=False)
    op.alter_column("user", "favorite_artists", nullable=False)
    op.alter_column("user", "unskippable_albums", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "unskippable_albums")
    op.drop_column("user", "favorite_artists")
    op.drop_column("user", "is_public")
    op.drop_constraint("playlist_source_id_fkey", "playlist", type_="foreignkey")
    op.drop_column("playlist", "source_id")
    op.drop_table("user_favorite_playlists")
    # ### end Alembic commands ###
