"""add_playlist_status_and_provider_fields

Revision ID: 284fa97d5297
Revises: 7317f7390757
Create Date: 2026-01-03 16:45:18.468988

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "284fa97d5297"
down_revision: Union[str, Sequence[str], None] = "7317f7390757"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("playlist", sa.Column("status", sa.String(length=50), nullable=False))
    op.add_column("playlist", sa.Column("provider", sa.String(length=50), nullable=True))
    op.add_column("playlist", sa.Column("provider_id", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("playlist", "provider_id")
    op.drop_column("playlist", "provider")
    op.drop_column("playlist", "status")
    # ### end Alembic commands ###
