"""add credentials to service_connection

Revision ID: b4fe00f3c024
Revises: e1aee7cbdc63
Create Date: 2026-01-02 04:16:26.525565

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b4fe00f3c024"
down_revision: Union[str, Sequence[str], None] = "e1aee7cbdc63"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("service_connection", sa.Column("credentials", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("service_connection", "credentials")
    # ### end Alembic commands ###
