"""change_favorite_artists_to_any

Revision ID: e1aee7cbdc63
Revises: 09010338c349
Create Date: 2026-01-02 03:11:10.383747

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "e1aee7cbdc63"
down_revision: Union[str, Sequence[str], None] = "09010338c349"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
